title: Jukskei
hero_image: images/banner.png
description: Créez votre propre jeu de jukskei avec Scratch !
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: Ce que tu feras
  - title: Joueur
    completion: engaged
  - title: Skey
  - title: Cheville
    completion: internal
  - title: Défi
    challenge: true
  - title: Que pouvez-vous faire maintenant ?
    completion: external
