title: Jukskei
hero_image: images/banner.png
description: Crée ton jeu Jukskei avec Scratch
version: 1
listed: true
copyedit: true
last_tested: "2026-01-08"
steps:
  - title: Ce que tu vas faire
  - title: Joueur
    completion: engaged
  - title: Skei
  - title: Piquet
    completion: internal
  - title: Défi
    challenge: true
    completion: external
